'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Confirm

    '''<summary>
    '''successPanel 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents successPanel As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''login 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents login As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''errorPanel 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents errorPanel As Global.System.Web.UI.WebControls.PlaceHolder
End Class
